CXX					=	gcc
CXX_STD				=	c99
CXXFLAGS			=	-Wall -Wextra -Werror -std=$(CXX_STD)

RUN_MSG				=	"READY"
BUILD_MSG			=	"BUILDING"
CLEAN_MSG			=	"CLEANING"
FCLEAN_MSG			=	"FILE CLEANING"
LINK_MSG			=	"LINKING"
REMAKE_MSG			=	"REMAKING"